### PR TITLE
NO JIRA Console branding/style improvements

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Remove Italics in logo.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@mtaylor just to align it more with the activemq logo, which doesn't have italics, also css to match. hoping it keeps you still happy.

**Comment by mtaylor** [comment]
Looks good thanks @michaelandrepearce

**Comment by mtaylor** [comment]
FYI I squashed the PR into 2 commits.  My original PR plus your changed.  Cheers.

**Comment by mtaylor** [comment]
Actually Michael on this one.  I'm not sure the change looks quite right with the last commit included.  I realise that these are mostly personal preference things. But let me take another stab at the logo.  If the issue is mostly the font size and italic I can change it but keep the rest the same?

**Comment by mtaylor** [comment]
How about this one.  Keeping the sizing the same on the login page.

console-logo2

**Comment by mtaylor** [comment]
console-logo2
This is pretty much the same as before but without italics

**Comment by michaelandrepearce** [comment]
Agreed it's all personal pref,

The second one looks good (better than the first as text is vertically centred), my main concern was italics mostly, not so much the size or text size.

29332137-e200dbda-81f6-11e7-80ae-f6fc913962c2

my only request would be if could you remove italics on the word apache on this one?

I assume the background will be transparent, just on black to visualise for now.

**Comment by michaelandrepearce** [comment]
Also can you make background transparent.

**Comment by mtaylor** [comment]
Yes no problem.  Cheers.

**Comment by mtaylor** [comment]
logo3

_No more italics!!!_ 

Final version will have transparent bg

**Comment by michaelandrepearce** [comment]
-1 just for that comment in italics :P 

In all seriousness , Looks great :)

**Pull request merged**
